name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit
        run: curl -I https://onlinepavadzimes-eszcghpbd8upg2u7jz9df8.streamlit.app/
